### ISSUE TITLE
dmenu-like mode

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#100]
Most good launchers offer a dmenu-like mode so users can scripts things.

F.e. `echo -e "first\nsecond\nthird" | dmenu`

This should be added.

**Comment by adamperkowski** [comment]
Please re-format this issue as an actual feature request.

**Comment by abenz1267** [comment]
What more clarification do you need?

**Comment by adamperkowski** [comment]
> What more clarification do you need?

Again, I understand. I asked **re-formatting** of this issue to make it a feature request.
