### ISSUE TITLE
desktop applications: can't search for filename

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#102]
F.e. searching for `nwg-look` should result in showing the appropriate desktop entry.

**Comment by nnyyxxxx** [comment]
all desktop entries are already shown by default

**Comment by nnyyxxxx** [comment]
![image](https://github.com/user-attachments/assets/180dac70-d547-415a-a5c3-04100d2afd18)
if its not in one of these locations then it wont be shown

**Comment by abenz1267** [comment]
It is.

**Comment by nnyyxxxx** [comment]
> Install nwg-look. Search for `nwg`.
> 
> ![image](https://private-user-images.githubusercontent.com/7055955/388098282-c58f03fe-7234-4a62-9e24-07a9ebeb8139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzg5MzEsIm5iZiI6MTczMzA3ODYzMSwicGF0aCI6Ii83MDU1OTU1LzM4ODA5ODI4Mi1jNThmMDNmZS03MjM0LTRhNjItOWUyNC0wN2E5ZWJlYjgxMzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDFUMTg0MzUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzJlYTMwNTMwNjBkOWM0ZjU0NWNjNmM5OWMxM2QwM2NhNTlhOGFmNDBjZWY0YTYxNTk2ODk2OWRjN2U2YTA1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.EYuVUvBnI74-vCxnS3xpBc9QtKvB71FF44cQcloffD8)
> 
> This should be shown. It isn't.

seems to be shown for me:

![image](https://github.com/user-attachments/assets/ebfd9432-3007-4d3d-bcb0-230d623b48da)

**Comment by abenz1267** [comment]
Dunno why you just close this.

I've just tried latest git (1bbd4ca9):

![image](https://github.com/user-attachments/assets/26714e0e-62d6-44b2-aa55-8796877fb014)

Walker: 
![image](https://github.com/user-attachments/assets/3545dd46-10ac-4179-ba9b-85e944cd54fb)

**Comment by nnyyxxxx** [comment]
```
[Desktop Entry]
Type=Application
Name=GTK Settings
```

if you search for "GTK Settings", then it will show up. This is clearly not a problem with hyprlauncher

**Comment by abenz1267** [comment]
The title clearly says: "can't search for filename". The filename for the desktop file is "nwg-look". You can't search for "nwg" and get the proper result.

Can't be more clear.
