### ISSUE TITLE
finder: unclear about what's the point of it

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#103]
Usually finders let you fuzzy find files on your system, in case of Hyprlauncher that's not the case. It doesn't even filter anything. It basically does nothing useful.

It doesn't even seem to work correctly at all. F.e. even if i scroll down into a folder and open it, all it does it put the path into the searchbar, but nothing else.

It should also hide all hidden (dot) folders by default.

**Comment by abenz1267** [comment]
You have an undocumented functionally and it's 100% unclear about what it should be doing or what your intentions for the feature even are.

I was merely illustrating the issue and what other good launchers are doing.

Not sure what's unclear to you here.

**Comment by adamperkowski** [comment]
> Not sure what's unclear to you here.

I don't understand the point of this issue. It's just stating your opinions (example: "It basically does nothing useful."), there is no issue to solve. A feature request would be that issue, for example.
See https://github.com/hyprutils/hyprlauncher/issues/98#issuecomment-2487726299

**Comment by abenz1267** [comment]
The point of the feature is to point out that you have a feature that is:

1) broken => you can fix this
2) not good => it's useless in the context of a launcher
3) it shows .-files by default => should be hidden by default

Can't be more clear really.
