### ISSUE TITLE
hyprlauncher seems to keep writing to the config file

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#108]
This behavior is annoying when editing the config while hyprlauncher is running.

https://github.com/user-attachments/assets/d10e9480-d8ca-4be2-bdf4-4d6b8a018fd3

See this video. This should not happen.

**Comment by nnyyxxxx** [comment]
this is intentional

**Comment by abenz1267** [comment]
... intentionally annoying? Why can't this be changed? What would break?
