### ISSUE TITLE
Wrong layer , not registered as client ( just feedback close if invalid)

### ISSUE THREAD

**Issue by bertSN1601** [hyprutils/hyprlauncher#109]
wrong layer and wrong name in layers (output hyprctl layers)
	Layer level 2 (top):
		Layer 5702bc9549d0: xywh: 0 0 3840 40, namespace: ironbar
		Layer 5702bc4f2930: xywh: 1624 804 600 600, namespace: gtk4-layer-shell

It really should be in the overlay layer and called hyprlauncher iso gtk4-layer-shell. as a consequence you need the debug option to disable focus and is the window still visible when moving to another workspace ( it should not in my view ) 

hyprctl clients does not display hyprlauncher , consequence is also that standard hyprland properties such as active border color do not apply. 

I would like to be able to use this fast and minimal launcher but currently these prevent me from using it.

**Comment by nnyyxxxx** [comment]
this is intentional, walker does the same
