### ISSUE TITLE
show apps in grid option

### ISSUE THREAD

**Issue by dougg0k** [hyprutils/hyprlauncher#110]
Hi,

Could you add grid like option rather than list?

Similar to https://github.com/elementary/applications-menu and https://user-images.githubusercontent.com/101165014/157171778-9f86a297-317c-4424-a5c5-d12b0866a677.png

Where you can also resize the menu and icons. That would be nice.

---

There are many options that use list, yet those that do not, are usually bloated or hard to install. Also usually lack customizations.

**Comment by nnyyxxxx** [comment]
MRs welcome
