### ISSUE TITLE
finder shows wrong icons

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#111]
![image](https://github.com/user-attachments/assets/c2c0ef83-1044-4246-91c3-cd25f8513c45)

The finder only shows generic icons. It should show the actual file type icons.

**Comment by nnyyxxxx** [comment]
MRs welcome

**Comment by nnyyxxxx** [comment]
finder functionality has been nuked and is being redone. This issue is no longer valid
