### ISSUE TITLE
desktop actions are not shown unless full name is typed

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#124]
Version:  git 78695c0b

![image](https://github.com/user-attachments/assets/e97c8aa9-f6a3-4de0-8119-2e477c726b41)

Desktop applications are still not shown.

**Comment by nnyyxxxx** [comment]
please read the commit names

**Comment by abenz1267** [comment]
Well, it's not documented and you can't expect people to read the commits to identify how a feature works.

That said: that's the worst way to implement the feature.

![image](https://github.com/user-attachments/assets/f20f492a-f700-4774-9712-82d91170c400)

![image](https://github.com/user-attachments/assets/d3f37081-3a15-49ea-a6e2-b11aa6335793)

![image](https://github.com/user-attachments/assets/7189e7b6-b1c6-474f-8143-aeb7fc74b990)

Makes no sense.

**Comment by nnyyxxxx** [comment]
i agree ngl

**Comment by abenz1267** [comment]
![image](https://github.com/user-attachments/assets/60bdabe2-701a-4c1b-8fbd-cfdaedb2ee7d)

i'm on commit 7c065fce (latest).

Quick advice: stop closing issues. Either OP closes the issue or you IF YOU ARE SURE IT CAN BE CLOSED. You keep closing and reopening issues.

**Comment by nnyyxxxx** [comment]
it was changed to a togglable feature, off by default. Documentation was added to configuration.md. Read up.

**Comment by abenz1267** [comment]
You should add that information when closing the issue instead of just closing it without providing the solution.

You can't expect people to read the whole documentation everytime you close an issue.
