### ISSUE TITLE
Finder is broken

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#125]
![image](https://github.com/user-attachments/assets/fcb1b0af-b79f-4847-a500-4148c3322642)

It just clears everything when searching.

**Comment by nnyyxxxx** [comment]
~Docu -> ~/Docu

**Comment by abenz1267** [comment]
It's still broken in general:

https://github.com/user-attachments/assets/9a99d575-6a08-4cf4-8244-c99afe7f6d33

It's pretty useless when you can't just fuzzy-search the filesystem, as you'd do with other launchers.

**Comment by nnyyxxxx** [comment]
> It's still broken in general:
> 2024-12-02-060712.mp4
> 
> It's pretty useless when you can't just fuzzy-search the filesystem, as you'd do with other launchers.

the cap issue was fixed in https://github.com/hyprutils/hyprlauncher/commit/78695c0b6fb5c5d8f70470b720017c818eb84114

**Comment by abenz1267** [comment]
Can confirm that's fixed.

Still the whole feature is ... useless? Like: using fzf in a terminal is more efficient. Why would i use this finder instead? It's not even a finder... it doesn't find anything (unless in same folder level).

**Comment by nnyyxxxx** [comment]
suggestions on what to change it to are welcome

**Comment by abenz1267** [comment]
Just add fuzzy filesystem searching similar to fzf.
