### ISSUE TITLE
websearch improvements

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#132]
Just do what Walker is doing:
- let people define their own search urls
- allow prefixes

That way people can add whatever search engine they want to use. F.e. i have google and youtube.

**Comment by nnyyxxxx** [comment]
can you explain what prefixes are?

**Comment by abenz1267** [comment]
`yt:somevideo` would explicity use the defined youtube search url.

![image](https://github.com/user-attachments/assets/a4b45eb4-893f-4928-9bc0-e41f84083111)

or

![image](https://github.com/user-attachments/assets/01557327-e792-408b-8a00-24cd57926073)

**Comment by nnyyxxxx** [comment]
wouldnt the user have to define youtube somewhere for youtube to work? or am i missing something

**Comment by nnyyxxxx** [comment]
ah i see now
