### ISSUE TITLE
Option "anchor: 'center'" not work on Gnome 4k monitor

### ISSUE THREAD

**Issue by taminhtienhai** [hyprutils/hyprlauncher#137]
## System Specification

**OS**: Arch Linux x86_64  
**Kernel**: Linux 6.12.1-2-cachyos  
**CPU**: AMD Ryzen 7 8845HS w/ Radeon 780M  
**DE**: GNOME 47.2  
**Display (LG ULTRAFINE)**: 3840x2160 @ 60  

## Issue

The launcher doesn't open centered on the screen. I've tried changing the margin-left to 200, but it hasn't made a difference.

## Screenshot

![image](https://github.com/user-attachments/assets/1321174d-ccd8-4a26-b978-cb80ed5ff1af)

**Comment by nnyyxxxx** [comment]
wayland is required for the layer shell to work, otherwise most options inside of the config wont work

**Comment by nnyyxxxx** [comment]
i'm going to close this as it's evident that you're on X11 and not Wayland

**Comment by taminhtienhai** [comment]
> i'm going to close this as it's evident that you're on X11 and not Wayland

It's Wayland. I used `yay` to install the bin package, which also installed `gtk4-layer-shell-1.0.4-1.2`. Is this the 'layer shell' you mentioned?

**Comment by nnyyxxxx** [comment]
yes
