### ISSUE TITLE
rapid input + ctrl+h gives main application list back

### ISSUE THREAD

**Issue by nnyyxxxx** [hyprutils/hyprlauncher#145]
![image](https://github.com/user-attachments/assets/3d454ce2-2a0b-48d5-85fe-498a242acd2f)

**Comment by abenz1267** [comment]
Why does this even need to be a keybind. ctrl+backspace is vanilla behaviour and works in every application and doesn't break this.

**Comment by nnyyxxxx** [comment]
no whitespace trimming
