### ISSUE TITLE
when searching for something, the first item should always be selected

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#147]
![image](https://github.com/user-attachments/assets/2da42b90-b80f-466e-837a-f81c4a03ced5)

As you can see here, it selects the wrong item, because of mouse-hover.

**Comment by nnyyxxxx** [comment]
fuzzel does the same thing

**Comment by abenz1267** [comment]
Puh.... ok.. if fuzzel does the same thing, there's no need to improve upon it. /s
