### ISSUE TITLE
UX suggestions

### ISSUE THREAD

**Issue by yavorski** [hyprutils/hyprlauncher#34]
Hi, the menu looks very nice OOB. Here are some suggestions for improvement:

* `CTRL + W ` - Delete word
* `CTRL + N`  - Select Next item
* `CTRL + P`  - Select Prev item

The "focus" part is not so nice, it would be better if you can always type and filter, without the need to hit "<kbd>/</kbd>" to type again.

**Comment by adamperkowski** [comment]
> The "focus" part is not so nice, it would be better if you can always type and filter, without the need to hit "/" to type again.

I agree. Would be much easier if the search entry focused when any key is being pressed.

**Comment by nnyyxxxx** [comment]
@adamperkowski will do this, will be a piece of cake.

**Comment by nnyyxxxx** [comment]
meh. I prefer how it is currently, however we converted to using gtk-layer-shell, so now focus will be held on hyprlauncher while its open; additionally unfocusing from the search bar is now harder because of that.

**Comment by nnyyxxxx** [comment]
will be implemented in #80

**Comment by nnyyxxxx** [comment]
along with many other performance improvements

**Comment by yavorski** [comment]
Great, it's working much better now!
Could we have the ability to remap keys, particularly the ones I mentioned in my earlier comment?
For reference, Fuzzel uses these keymaps as defaults, and I believe others might appreciate having them as well.

**Comment by nnyyxxxx** [comment]
well, currently we dont have any custom navigation keys other than vim_keys, but yes i can add a custom set of keys to navigate. will be configurable in the config file as always

**Comment by nnyyxxxx** [comment]
also i'm open for suggestions about features, if you could open an issue with a sh*t ton of features you would like to see in hyprlauncher that would mean the world

**Comment by yavorski** [comment]
Not a lot of features I can think of, maybe run/drun modes would be nice as well, but I'm sure you have this already in mind.

**Comment by nnyyxxxx** [comment]
> Not a lot of features I can think of, maybe run/drun modes would be nice as well, but I'm sure you have this already in mind.

sounds like a good feature, currently we do technically have both run and drun modes combined BUT its exclusive to full binary names to actually see the entries located in /usr/bin.

for instance:
![image](https://github.com/user-attachments/assets/33c99424-f918-4b1b-b922-83952d6719f9)

**Comment by yavorski** [comment]
Great, I have just installed id, it works great with the new keymaps and the ability to customize it!

In order to allow all kind of user further customization, I would suggest to leave the the default css file as stand alone file and give the user complete control to override it, instead of hardcoding it in the rust source. Just put default values there, and remove the styling options from `config.json`. It would be easier to me just edit/customize the css file instead, as it would allow more control and custom styling and the benefit of this is that you would not need to handle it with code.

For the run/drun menu it would be nice have docs how to run a custom command, such as `btm` for example or passing cli flags like `btm --basic --tree` and how to make it work with hyprlauncher. CLI flags would be helpful too for example `hyprlauncer --drun`  and `hyprlauncer --run` etc, one of them being the default.

Nice work, Thank you!

**Comment by nnyyxxxx** [comment]
> Great, I have just installed id, it works great with the new keymaps and the ability to customize it!
> 
> In order to allow all kind of user further customization, I would suggest to leave the the default css file as stand alone file and give the user complete control to override it, instead of hardcoding it in the rust source. Just put default values there, and remove the styling options from `config.json`. It would be easier to me just edit/customize the css file instead, as it would allow more control and custom styling and the benefit of this is that you would not need to handle it with code.
> 
> For the run/drun menu it would be nice have docs how to run a custom command, such as `btm` for example or passing cli flags like `btm --basic --tree` and how to make it work with hyprlauncher. CLI flags would be helpful too for example `hyprlauncer --drun` and `hyprlauncer --run` etc, one of them being the default.
> 
> Nice work, Thank you!

having a standalone CSS file is not this projects goal, more extensibility will be added, and everything will be done in the main config file. Hyprlauncher was made to be dead simple to configure and use, and it will be. more config values will be added in the future to allow complete customization of the CSS file without actually knowing CSS! No skill required to use and jump in, only reading basic documentation.

Now for cli arguments i'm not really sure if i want to do that, I currently want to have everything in the config file; maybe we could have a nested section inside of the window section that allows the user to pick drun or run; this will be done because hyprlauncher is not like other launchers (very important) we have live config reloading meaning configuration can be done live while the launcher is open, you wont have to restart and use cli args to use drun or run, just edit the file and boom changes made live!

**Comment by yavorski** [comment]
Sounds good.

**Comment by nnyyxxxx** [comment]
presumably a plugin system will be added in the future that could allow separating the CSS from the code, idk though, thoughts for now
