### ISSUE TITLE
XDG_DATA_DIRS and PATH removed?

### ISSUE THREAD

**Issue by arminius-smh** [hyprutils/hyprlauncher#53]
Hello, on v.0.1.3 hyprlauncher used to scan the 'XDG_DATA_DIRS' and 'PATH' variable however v0.1.4 with commit https://github.com/hyprutils/hyprlauncher/commit/004c5f8dc76c1b96e3951e7153fb365f5bd89b0f removed both of these options, I guess it is your decision if the whole PATH should be included or only applications that have desktop files, but it would be nice if 'XDG_DATA_DIRS' could be included again since right now almost no applications gets shown on nixos/systems that dont follow the hardcoded paths

<details>
  <summary>0.1.3</summary>

![2024-11-14_16-09-15_screenshot](https://github.com/user-attachments/assets/bd9a27f8-811d-4b05-afbf-dc7bed8efc02)

</details>

<details>
  <summary>0.1.4</summary>

![2024-11-14_16-08-18_screenshot](https://github.com/user-attachments/assets/3e0bea50-be40-4e0f-bbe1-248c53044dc3)

</details>

**Comment by nnyyxxxx** [comment]
oh sorry, i don't use NixOS.

Will do a following release after adding it back, as i was planning to with the merge of https://github.com/hyprutils/hyprlauncher/pull/54

**Comment by nnyyxxxx** [comment]
https://github.com/hyprutils/hyprlauncher/commit/ff6e7f47d408fcb7c45761dd21fa28434676e78f

**Comment by nnyyxxxx** [comment]
lmk if that commit fixes your problem, I will make a release after

**Comment by arminius-smh** [comment]
Thanks a lot, this fixed it 👍

![2024-11-14_16-24-54_screenshot](https://github.com/user-attachments/assets/59f67021-8a05-4a74-87ab-9400c77e9884)
