### ISSUE TITLE
Can't install required gtk4-layer-shell from AUR

### ISSUE THREAD

**Issue by dezyh** [hyprutils/hyprlauncher#87]
It might just be me, but the AUR package fails to install because it can't find [gtk4-layer-shell](https://archlinux.org/packages/extra/x86_64/gtk4-layer-shell/) despite it seemingly existing on the AUR.

```
$ yay -S hyprlauncher
 -> No AUR package found for gtk4-layer-shell
 -> could not find all required packages: gtk4-layer-shell
```
```
$ yay -Ss gtk4-layer-shell
aur/vlsh-git r2.9d518c5-1 (+0 0.00)
    gtk4-layer-shell video wallpaper
```

**Comment by adamperkowski** [comment]
That's because gtk4-layer-shell is not in the AUR. It's in arxh/extra. The URL you provided leads to extra.

Even if it did fail to install, it's not in any way an issue with Hyprlauncher. 

Friendly advice: use paru, not yay. It's faster and can also install from the pacman repos.
