### ISSUE TITLE
Pressing / while not focused in search doesnt focus it

### ISSUE THREAD

**Issue by JumpIn-Git** [hyprutils/hyprlauncher#89]
When you unfocus from the search bar, it tells you to press / to focus, but this doesnt work

**Comment by nnyyxxxx** [comment]
can you send a video please, i'm not even sure that you can unfocus from the search bar unless you have 

```json
  "debug": {
    "disable_auto_focus": true
  }
```

set to true

**Comment by abenz1267** [comment]
> When you unfocus from the search bar, it tells you to press / to focus, but this doesnt work

can confirm.

**Comment by nnyyxxxx** [comment]
can you explain how you are unfocusing from the search bar?, it's not even possible

**Comment by nnyyxxxx** [comment]
ah i see, arrow keys

**Comment by abenz1267** [comment]
This isn't fixed.

**Comment by nnyyxxxx** [comment]
what's not fixed?

**Comment by nnyyxxxx** [comment]
leaving the search bar is impossible
