### ISSUE TITLE
ability to run commands in terminal

### ISSUE THREAD

**Issue by abenz1267** [hyprutils/hyprlauncher#99]
Currently there's no way to run a command in a new terminal window. F.e. running `yay` from Hyprlauncher is pointless.

**Comment by adamperkowski** [comment]
Please re-format this issue as an actual feature request.

**Comment by abenz1267** [comment]
What more clarification do you need?

Certain commands need to be run in a terminal window, f.e. `yay`. With hyprlauncher there's no way of achieving that.

**Comment by adamperkowski** [comment]
> What more clarification do you need?
>
> Certain commands need to be run in a terminal window, f.e. yay. With hyprlauncher there's no way of achieving that.

Again, I understand. I asked **re-formatting** of this issue to make it a feature request.

**Comment by nnyyxxxx** [comment]
> Currently there's no way to run a command in a new terminal window. F.e. running `yay` from Hyprlauncher is pointless.

"disable_auto_focus" is very clearly inside of the config and mentioned inside of configuration.md
